// src/view/components/Navbar.tsx
import React, { useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import Data from '../../model/data/navData.json'

const navList = Data.navbar

const Navbar: React.FC = () => {
    const [trigger, setTrigger] = useState(false)

    const location = useLocation()

    const onClickEvent = () => {
        setTrigger(!trigger)
    }
    return (
        <>
            {/* Sidebar */}
            <aside
                className={`fixed right-0 top-0 z-50 h-full w-[254px] bg-white/5 backdrop-blur-lg transition-transform duration-300 ${
                    trigger ? 'translate-x-0' : 'translate-x-full'
                }`}
            >
                <div className="m-auto flex h-[86.99px] w-[190px] items-center justify-end">
                    <img
                        className="h-[19.09px] w-[19.09px]"
                        src="/assets/shared/icon-close.svg"
                        alt="close icon"
                        onClick={onClickEvent}
                    />
                </div>
                <ul className="m-auto mt-[31px] h-[172px] w-[190px]">
                    {navList.map((list, i) => (
                        <li
                            className="mb-[32px] leading-[normal] tracking-[2.7px] text-white"
                            key={i}
                        >
                            <Link to={list.link} onClick={onClickEvent}>
                                <h2>
                                    <span className="font-bold">
                                        {list.numlist}
                                    </span>{' '}
                                    <span className="text-white/80">
                                        {list.title}
                                    </span>
                                </h2>
                            </Link>
                        </li>
                    ))}
                </ul>
            </aside>

            {/* Overlay */}
            {trigger && (
                <div
                    className="fixed left-0 top-0 z-40 h-full w-full bg-black opacity-50"
                    onClick={onClickEvent}
                />
            )}

            <div className="m-auto flex h-full w-[327px] items-center justify-between tracking-[2.36px] md:m-0 md:w-[729px] md:text-[14px] lg:w-dependWidth xl:h-[96px] xl:w-[1385px] xl:text-[16px] xl:tracking-[2.7px]">
                <Link to={'/'}>
                    <img
                        className="h-[40px] w-auto md:h-[48px]"
                        src="/assets/shared/logo.svg"
                        alt="Logo"
                    />
                </Link>

                <img
                    className="h-[21px] w-auto sm:hidden"
                    src="/assets/shared/icon-hamburger.svg"
                    alt="hamburger-button"
                    onClick={onClickEvent}
                />
                <div className="relative hidden xl:flex xl:h-full xl:w-[507px] xl:items-center">
                    <div className="absolute left-[64px] z-10 h-[1px] w-[473px] bg-white/15"></div>
                </div>
                {/* Tablet & Desktop Viewport */}
                <div className="hidden md:block md:h-full md:w-[450px] md:bg-white/5 md:text-white md:backdrop-blur-lg xl:w-[830px]">
                    <ul className="m-auto flex h-full w-[356px] items-center justify-between xl:w-[542px]">
                        {navList.map((list, i) => (
                            <li className="h-full" key={i}>
                                <Link
                                    className={`flex h-full items-center border-b-[3px] border-solid ${location.pathname === list.link ? 'border-white' : 'border-white/0 text-white/70 hover:border-white/30'}`}
                                    to={list.link}
                                >
                                    <h2 className="flex text-white/80">
                                        <span className="hidden font-bold text-white xl:mr-[11px] xl:block">
                                            {list.numlist}
                                        </span>
                                        {list.title}
                                    </h2>
                                </Link>
                            </li>
                        ))}
                    </ul>
                </div>
            </div>
        </>
    )
}

export default Navbar

// src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterLink, RouterLinkActive],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css',
})
export class NavbarComponent {
  logo: string;
  linkers: linkerList[];

  constructor() {
    this.logo = '../../../assets/shared/logo.svg';
    this.linkers = [
      {
        name: 'HOME',
        num: 0,
        path: '/home',
      },
      {
        name: 'DESTINATION',
        num: 1,
        path: '/destination',
      },
      {
        name: 'CREW',
        num: 2,
        path: '/crew',
      },
      {
        name: 'TECHNOLOGY',
        num: 3,
        path: 'technology',
      }
    ];
  }
}

interface linkerList {
  name: string;
  num: number;
  path: string;
}

<header
  class="fixed left-0 top-[40px] right-0 flex justify-between items-center z-[20]"
>
  <figure class="ml-[55px]">
    <img [src]="logo" alt="Space Tourism Logo" class="w-[48px]" />
  </figure>
  <div
    class="bg-white/[0.2515] w-[300px] laptop:w-[473px] h-[1px] absolute left-[167px] z-[10]"
  ></div>
  <nav
    class="w-[830px] h-[96px] bg-white/[0.04] backdrop-blur-[40.77px] flex pl-[123px] gap-[50px]"
  >
    @for (linker of linkers; track linker.name) {
    <li
      [routerLink]="linker.path"
      routerLinkActive="border-b-white hover:border-b-white"
      [routerLinkActiveOptions]="{ exact: true }"
      class="flex items-center gap-[11px] cursor-pointer border-b-[3px] border-b-transparent hover:border-b-white/[0.5021] transition-all ease-in-out duration-300 select-none"
    >
      <span class="font-bold tracking-[2.7px] font-barlowCondensed text-white"
        >0{{ linker.num }}</span
      ><a class="text-white tracking-[2.7px] font-barlowCondensed">{{
        linker.name
      }}</a>
    </li>
    }
  </nav>
</header>
