// src/app/pages/destination/destination.component.ts
import { CommonModule, NgClass, NgStyle } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { Destination, RootObject } from '../../interfaces/global';
import { GlobalService } from '../../services/global.service';
import {
  animate,
  state,
  style,
  transition,
  trigger,
  AnimationEvent,
} from '@angular/animations';

@Component({
  selector: 'app-destination',
  standalone: true,
  imports: [NgStyle, NgClass, CommonModule],
  templateUrl: './destination.component.html',
  styleUrl: './destination.component.css',
  animations: [
    trigger('myAnimation', [
      state('start', style({
        transform: 'translateX(0)',
        opacity: 1
      })),
      state('end', style({
        transform: 'translateX(-100px)',
        opacity: 0
      })),
      transition('start => end', animate('1s ease-in-out', style({
        transform: 'translateX(100px)',
        opacity: 0,
      }))),
      transition('end => start', animate('1s ease-in-out', style({
        transform: 'translateX(0)',
        opacity: 1,
      }))),
    ]),
    trigger('imageAnimation', [
      state('start', style({
        transform: 'scale(1)',
        opacity: 1
      })),
      state('end', style({
        transform: 'scale(1.5)',
        opacity: 0
      })),
      transition('start => end', animate('1s ease-in-out', style({
        transform: 'scale(0.2)',
        opacity: 0,
      }))),
      transition('end => start', animate('1s ease-in-out', style({
        transform: 'scale(1)',
        opacity: 1,
      }))),
    ]),
  ],
})
export class DestinationComponent implements OnInit {
  allData: RootObject = inject(GlobalService).globalData;
  planetData: Destination[];
  backgroundImage: string;
  state: string;
  content: Destination | undefined;
  query: string;

  constructor() {
    this.backgroundImage =
      "url('../../../assets/destination/background-destination-desktop.jpg')";
    this.planetData = this.allData.destinations;
    this.state = 'start';
    this.query = 'Moon';
    this.content = this.planetData.find((planet) => planet.name === this.query);
  }

  ngOnInit(): void {
    console.log(this.content)
  }

  toggle(value: string): void {
    if(this.query !== value) {
      this.state = 'end';
      this.query = value;
    }
  }

  animationDone(event: AnimationEvent) {
    if (event.toState === 'end') {
      this.state = 'start';
      this.content = this.planetData.find((planet) => planet.name === this.query);
    }
  }
}

<main class="w-full min-h-screen bg-cover bg-center overflow-hidden" [ngStyle]="{ 'background-image': backgroundImage}">
  <section class="pt-[212px] pb-[118px] px-[166.5px] flex flex-col animate-summon gap-[64px]">
    <div class="font-barlowCondensed tracking-[4.725px] flex items-center gap-[28px]">
      <p class="text-white/[0.25] text-[28px] font-bold">01</p>
      <p class="text-[28px] text-white">PICK YOUR DESTINATION</p>
    </div>
    <section class="flex items-center justify-between">
      <figure class="flex-1 flex justify-center items-center" [@imageAnimation]="state" (@imageAnimation.done)="animationDone($event)">
        <img [src]=content?.images?.png alt="Destination Image" class="animate-rotation rounded-full">
      </figure>
      <section class="flex-1 pl-[100px]">
        <nav class="flex gap-[36px]">
          <button class="text-textColor tracking-[2.7px] font-barlowCondensed pb-[12px] border-b-[3px] border-b-transparent hover:border-b-white/50 transition-all ease-in-out duration-300" [ngClass]="{'border-b-white hover:border-b-white/100 text-white': content?.name === 'Moon'}" (click)="toggle('Moon')">MOON</button>
          <button class="text-textColor tracking-[2.7px] font-barlowCondensed pb-[12px] border-b-[3px] border-b-transparent hover:border-b-white/50 transition-all ease-in-out duration-300" [ngClass]="{'border-b-white hover:border-b-white/100 text-white': content?.name === 'Mars'}" (click)="toggle('Mars')">MARS</button>
          <button class="text-textColor tracking-[2.7px] font-barlowCondensed pb-[12px] border-b-[3px] border-b-transparent hover:border-b-white/50 transition-all ease-in-out duration-300" [ngClass]="{'border-b-white hover:border-b-white/100 text-white': content?.name === 'Europa'}" (click)="toggle('Europa')">EUROPA</button>
          <button class="text-textColor tracking-[2.7px] font-barlowCondensed pb-[12px] border-b-[3px] border-b-transparent hover:border-b-white/50 transition-all ease-in-out duration-300" [ngClass]="{'border-b-white hover:border-b-white/100 text-white': content?.name === 'Titan'}" (click)="toggle('Titan')">TITAN</button>
        </nav>
        <article [@myAnimation]="state" (@myAnimation.done)="animationDone($event)">
          <h1 class="text-white text-[100px] font-bellefair uppercase">{{ content?.name }}</h1>
          <p class="text-textColor text-[18px] leading-[32px] min-h-[170px]">{{ content?.description }}</p>
          <div class="flex text-textColor border-t-[1px] border-t-[#383B4B] pt-[28px]">
            <div class="flex-1">
              <p class="text-textColor text-[14px] font-barlowCondensed tracking-[2.362px]">AVG. DISTANCE</p>
              <p class="text-white text-[28px] font-bellefair uppercase">{{ content?.distance }}</p>
            </div>
            <div class="flex-1">
              <p class="text-textColor text-[14px] font-barlowCondensed tracking-[2.362px]">EST. TRAVEL TIME</p>
              <p class="text-white text-[28px] font-bellefair uppercase">{{ content?.travel }}</p>
            </div>
          </div>
        </article>
      </section>
    </section>
  </section>
</main>

// src/pages/Destination.tsx
import React, { useRef } from "react";
import BackgroundImage from "/assets/destination/background-destination-desktop.jpg";
import { useGlobal } from "../context/GlobalContext";
import PlanetSelector from "../components/PlanetSelector";
import "./Destination.css";
import {
  CSSTransition,
  SwitchTransition,
  TransitionGroup,
} from "react-transition-group";

const Destination: React.FC = () => {
  const { globalData, planet } = useGlobal();
  const selectedDestination = globalData.destinations.find(
    (destination) => destination.name.toLowerCase() === planet
  );
  const planetNames: string[] = ["moon", "mars", "europa", "titan"];
  const planetRefs = {
    moon: useRef<HTMLHeadingElement>(null),
    mars: useRef<HTMLHeadingElement>(null),
    europa: useRef<HTMLHeadingElement>(null),
    titan: useRef<HTMLHeadingElement>(null),
  };
  const planetImageRefs = {
    moonImage: useRef<HTMLImageElement>(null),
    marsImage: useRef<HTMLImageElement>(null),
    europaImage: useRef<HTMLImageElement>(null),
    titanImage: useRef<HTMLImageElement>(null),
  };
  const nodeRef = planetRefs[planet as keyof typeof planetRefs];
  const stringName = planet + "Image";
  const imageRef = planetImageRefs[stringName as keyof typeof planetImageRefs];

  return (
    <div
      className="w-full min-h-screen bg-cover text-white flex flex-col overflow-hidden"
      style={{ backgroundImage: `url(${BackgroundImage})` }}
    >
      <div className="w-full px-[10%] py-[7%] mt-auto flex flex-col gap-[64px] animate-summon">
        <div className="flex gap-[28px] items-center">
          <p className="font-barlowCondensed text-[28px] tracking-[4.725px] opacity-[0.25] text-white">
            01
          </p>
          <p className="font-barlowCondensed text-[28px] tracking-[4.725px] text-white">
            PICK YOUR DESTINATION
          </p>
        </div>
        <div className="flex justify-between items-center w-full">
          <TransitionGroup className="w-[50%] relative bg-red-500">
            <CSSTransition
              key={planet}
              nodeRef={imageRef}
              timeout={500}
              classNames="planet-transition"
            >
              <img ref={imageRef} src={selectedDestination?.images.png} alt="" className="w-[80%] animate-rotation absolute -top-[200px]" />
            </CSSTransition>
          </TransitionGroup>
          <div className="flex flex-col gap-[37px] w-[39%]">
            <div className="flex gap-[36px]">
              {planetNames.map((name) => (
                <PlanetSelector key={name} planetName={name} />
              ))}
            </div>
            <SwitchTransition mode="out-in">
              <CSSTransition
                key={planet}
                nodeRef={nodeRef}
                addEndListener={(done: () => void): void => {
                  nodeRef.current?.addEventListener(
                    "transitionend",
                    done,
                    false
                  );
                }}
                classNames="my-transition"
              >
                <div ref={nodeRef} className="flex flex-col gap-[37px]">
                  <div className="flex flex-col">
                    <h1 className="font-bellefair text-[100px] text-white">
                      {selectedDestination
                        ? selectedDestination.name.toUpperCase()
                        : ""}
                    </h1>
                    <p className="font-barlow text-[18px] leading-[32px] text-textColor">
                      {selectedDestination
                        ? selectedDestination.description
                        : ""}
                    </p>
                  </div>
                  <div className="flex border-t-[1px] border-t-[#383B4B] pt-[28px] gap-[79px] mt-[17px]">
                    <div>
                      <p className="font-barlowCondensed text-[14px] tracking-[2.362px] text-textColor">
                        AVG. DISTANCE
                      </p>
                      <p className="text-white font-bellefair text-[28px]">
                        {selectedDestination
                          ? selectedDestination.distance.toUpperCase()
                          : ""}
                      </p>
                    </div>
                    <div>
                      <p className="font-barlowCondensed text-[14px] tracking-[2.362px] text-textColor">
                        EST. TRAVEL TIME
                      </p>
                      <p className="text-white font-bellefair text-[28px]">
                        {selectedDestination
                          ? selectedDestination.travel.toUpperCase()
                          : ""}
                      </p>
                    </div>
                  </div>
                </div>
              </CSSTransition>
            </SwitchTransition>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Destination;
