// src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterLink, RouterLinkActive],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css',
})
export class NavbarComponent {
  logo: string;
  linkers: linkerList[];

  constructor() {
    this.logo = '../../../assets/shared/logo.svg';
    this.linkers = [
      {
        name: 'HOME',
        num: 0,
        path: '/home',
      },
      {
        name: 'DESTINATION',
        num: 1,
        path: '/destination',
      },
      {
        name: 'CREW',
        num: 2,
        path: '/crew',
      },
      {
        name: 'TECHNOLOGY',
        num: 3,
        path: 'technology',
      }
    ];
  }
}

interface linkerList {
  name: string;
  num: number;
  path: string;
}

<header
  class="fixed left-0 top-[40px] right-0 flex justify-between items-center z-[20]"
>
  <figure class="ml-[55px]">
    <img [src]="logo" alt="Space Tourism Logo" class="w-[48px]" />
  </figure>
  <div
    class="bg-white/[0.2515] w-[300px] laptop:w-[473px] h-[1px] absolute left-[167px] z-[10]"
  ></div>
  <nav
    class="w-[830px] h-[96px] bg-white/[0.04] backdrop-blur-[40.77px] flex pl-[123px] gap-[50px]"
  >
    @for (linker of linkers; track linker.name) {
    <li
      [routerLink]="linker.path"
      routerLinkActive="border-b-white hover:border-b-white"
      [routerLinkActiveOptions]="{ exact: true }"
      class="flex items-center gap-[11px] cursor-pointer border-b-[3px] border-b-transparent hover:border-b-white/[0.5021] transition-all ease-in-out duration-300 select-none"
    >
      <span class="font-bold tracking-[2.7px] font-barlowCondensed text-white"
        >0{{ linker.num }}</span
      ><a class="text-white tracking-[2.7px] font-barlowCondensed">{{
        linker.name
      }}</a>
    </li>
    }
  </nav>
</header>

// src/components/Navbar.tsx
import React from 'react';
import Icon from "/assets/shared/logo.svg";
import NavbarLinker from './NavbarLinker';

type linkerData = {
  path: string,
  id: number,
}

const Navbar: React.FC = () => {
  const linkerData: linkerData[] = [
    {
      path: "home",
      id: 0,
    },
    {
      path: "destination",
      id: 1,
    },
    {
      path: "crew",
      id: 2,
    }
  ];

  return (
    <div className='text-white fixed top-[40px] right-0 left-0 flex justify-between z-[20]'>
      <img src={Icon} alt="Space Logo" className='ml-[3%] py-[24px]' />
      <div className='bg-white/30 w-[39%] h-[1px] absolute top-[50%] left-[10%] z-10'></div>
      <div className='w-[53%] bg-white/[.04] backdrop-blur-[40px] flex justify-center gap-[60px] font-barlowCondensed'>
        {linkerData.map((prop) => (
          <NavbarLinker key={prop.path} path={prop.path} id={prop.id} />
        ))}
      </div>
    </div>
  )
}

export default Navbar
