// src/pages/Home.tsx
import React from "react";
import BackgroundImage from "/assets/home/background-home-desktop.jpg";
import { Link } from "react-router-dom";

const Home: React.FC = () => {
  return (
    <div
      className="w-full min-h-screen bg-cover text-white flex flex-col overflow-hidden"
      style={{ backgroundImage: `url(${BackgroundImage})` }}
    >
      <div className="p-[10%] flex items-end justify-between mt-auto gap-[20%] w-full select-none animate-summon">
        <div className="flex flex-col gap-[10px] flex-1">
          <p className="text-[28px] font-barlowCondensed text-textColor tracking-[4.725px]">
            SO, YOU WANT TO TRAVEL TO
          </p>
          <h1 className="text-[150px] font-bellefair">SPACE</h1>
          <p className="text-[18px] font-barlow leading-[32px] text-textColor">
            Let's face it; if you want to go to space, you might as well
            ganuinely go to outer space and not hover kind of on the edge of it.
            Well sit back, and relax because we'll give you a truly out of this
            world experience
          </p>
        </div>
        <div className="flex-1 flex justify-center">
          <div className="w-[60%] flex justify-center relative group">
            <Link to='/destination' className="text-[32px] text-[#0B0D17] font-bellefair tracking-[2px] bg-white w-full aspect-square rounded-full z-[10] select-none flex justify-center items-center">
              EXPLORE
            </Link>
            <div className="absolute bg-white/10 w-full group-hover:scale-[1.6] aspect-square rounded-full -top-0 transition-all ease-in-out duration-500"></div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;

// src/app/pages/home/home.component.ts
import { NgStyle } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [NgStyle, RouterLink],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent implements OnInit {
  backgroundImage: string;

  constructor() {
    this.backgroundImage = '';
  }

  ngOnInit(): void {
    this.backgroundImage = 'url(\'../../../assets/home/background-home-desktop.jpg\')';
  }
}

<main class="w-full min-h-screen bg-cover bg-center" [ngStyle]="{ 'background-image': backgroundImage}">
  <section class="px-[165.5px] pb-[131px] pt-[360px] flex justify-between items-end animate-summon">
    <article class="flex flex-col w-[445px]">
      <h3 class="font-barlowCondensed text-textColor text-[28px] tracking-[4.725px]">SO, YOU WANT TO TRAVEL TO</h3>
      <h1 class="font-bellefair text-white text-[150px]">SPACE</h1>
      <p class="text-textColor text-[18px] leading-[32px]">Let's face it; if you want to go to space, you might as well genuinely go to outer space and not hover kind of on the edge of it. Well sit back,and relax because we'll give you a truly out of this world experience!</p>
    </article>
    <section class="grow flex justify-end">
      <div class="w-[274px] aspect-square rounded-full group flex justify-center relative">
        <button routerLink="/destination" class="w-full aspect-square rounded-full bg-white flex justify-center items-center text-[#0B0D17] font-bellefair text-[32px] tracking-[2px] select-none z-[10]">EXPLORE</button>
        <div class="w-full aspect-square rounded-full bg-white/[0.1036] absolute group-hover:scale-[1.64] transition-all ease-in-out duration-300"></div>
      </div>
    </section>
  </section>
</main>
