// src/view/components/Home.tsx
import React from 'react'
import { Link } from 'react-router-dom'

const Home: React.FC = () => {
    return (
        <div className="mt-[28px] flex flex-col items-center justify-center md:mt-[106px] xl:mb-[131px] xl:mt-[251px]">
            <div className="w-[327px] text-white md:w-[450px] xl:flex xl:w-[1110px]">
                <div className="text-center xl:w-[450px] xl:text-start">
                    <h2 className="leading-[normal] tracking-[2.7px] text-white/75 md:text-[20px] md:tracking-[3.38px] xl:text-[28px]">
                        SO, YOU WANT TO TRAVEL TO
                    </h2>
                    <h1 className="my-[16px] text-[80px] leading-[100px] md:my-[24px] md:text-[150px] md:leading-[150px] xl:h-[172px] xl:w-[445px] xl:leading-[normal]">
                        SPACE
                    </h1>
                    <p className="text-[15px] leading-[25px] text-white/75 md:text-[16px] xl:text-[18px] xl:leading-[32px]">
                        Let's face it; if you want to go to space, you might as
                        well genuinely go to outer space and not hover kind of
                        on the edge of it. Well sit back, and relax because
                        we'll give you a truly out of this world experience!
                    </p>
                </div>
                <div className="mt-[33px] flex h-[246px] w-full items-center justify-center md:mb-[90px] md:mt-[156px] xl:m-0 xl:h-[382px] xl:items-end xl:justify-end">
                    <Link
                        to={'destination'}
                        className="relative flex h-[150px] w-[150px] items-center justify-center rounded-full bg-white text-blackCustom md:h-[242px] md:w-[242px] xl:h-[274px] xl:w-[274px]"
                    >
                        <div className="absolute h-[150px] w-[150px] rounded-full bg-white/10 transition-transform hover:scale-150 md:h-[242px] md:w-[242px] xl:h-[274px] xl:w-[274px]"></div>
                        <h1 className="text-center text-[20px] leading-[normal] tracking-[1.25px] md:text-[32px] md:tracking-[2px]">
                            EXPLORE
                        </h1>
                    </Link>
                </div>
            </div>
        </div>
    )
}

export default Home

// src/app/pages/home/home.component.ts
import { NgStyle } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [NgStyle, RouterLink],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent implements OnInit {
  backgroundImage: string;

  constructor() {
    this.backgroundImage = '';
  }

  ngOnInit(): void {
    this.backgroundImage = 'url(\'../../../assets/home/background-home-desktop.jpg\')';
  }
}

<main class="w-full min-h-screen bg-cover bg-center" [ngStyle]="{ 'background-image': backgroundImage}">
  <section class="px-[165.5px] pb-[131px] pt-[360px] flex justify-between items-end animate-summon">
    <article class="flex flex-col w-[445px]">
      <h3 class="font-barlowCondensed text-textColor text-[28px] tracking-[4.725px]">SO, YOU WANT TO TRAVEL TO</h3>
      <h1 class="font-bellefair text-white text-[150px]">SPACE</h1>
      <p class="text-textColor text-[18px] leading-[32px]">Let's face it; if you want to go to space, you might as well genuinely go to outer space and not hover kind of on the edge of it. Well sit back,and relax because we'll give you a truly out of this world experience!</p>
    </article>
    <section class="grow flex justify-end">
      <div class="w-[274px] aspect-square rounded-full group flex justify-center relative">
        <button routerLink="/destination" class="w-full aspect-square rounded-full bg-white flex justify-center items-center text-[#0B0D17] font-bellefair text-[32px] tracking-[2px] select-none z-[10]">EXPLORE</button>
        <div class="w-full aspect-square rounded-full bg-white/[0.1036] absolute group-hover:scale-[1.64] transition-all ease-in-out duration-300"></div>
      </div>
    </section>
  </section>
</main>
