// src/app/pages/crew/crew.component.ts
import { Component, inject } from '@angular/core';
import { Crew, RootObject } from '../../interfaces/global';
import { GlobalService } from '../../services/global.service';
import { CommonModule } from '@angular/common';
import {
  animate,
  state,
  style,
  transition,
  trigger,
  AnimationEvent,
} from '@angular/animations';

@Component({
  selector: 'app-crew',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './crew.component.html',
  styleUrl: './crew.component.css',
  animations: [
    trigger('myAnimation', [
      state('start', style({
        transform: 'translateX(0)',
        opacity: 1
      })),
      state('end', style({
        transform: 'translateX(-100px)',
        opacity: 0
      })),
      transition('start => end', animate('1s ease-in-out', style({
        transform: 'translateX(100px)',
        opacity: 0,
      }))),
      transition('end => start', animate('1s ease-in-out', style({
        transform: 'translateX(0)',
        opacity: 1,
      }))),
    ]),
  ],
})
export class CrewComponent {
  allData: RootObject = inject(GlobalService).globalData;
  backgroundImage: string;
  crewData: Crew[];
  state: string;
  query: string;
  content: Crew | undefined;

  constructor() {
    this.backgroundImage = 'url(\'../../../assets/crew/background-crew-desktop.jpg\')'
    this.crewData = this.allData.crew;
    this.state = 'start';
    this.query = "Douglas Hurley";
    this.content = this.crewData.find((crew) => crew.name === this.query);
  }

  toggle(value: string): void {
    if(this.query !== value) {
      this.state = 'end';
      this.query = value;
    }
  }

  animationDone(event: AnimationEvent): void {
    if (event.toState === 'end') {
      this.state = 'start';
      this.content = this.crewData.find((crew) => crew.name === this.query)
    }
  }
}

<main
  class="w-full min-h-screen bg-cover bg-center overflow-hidden"
  [ngStyle]="{ 'background-image': backgroundImage }"
>
  <section class="pt-[212px] px-[165px] animate-summon flex flex-col">
    <div
      class="font-barlowCondensed tracking-[4.725px] flex items-center gap-[28px]"
    >
      <p class="text-white/[0.25] text-[28px] font-bold">02</p>
      <p class="text-[28px] text-white">MEET YOUR CREW</p>
    </div>
    <section class="flex flex-row justify-between">
      <section class="pt-[154px] flex-1">
        <article
          [@myAnimation]="state"
          (@myAnimation.done)="animationDone($event)"
        >
          <h3 class="uppercase text-white/50 font-bellefair text-[32px]">
            {{ content?.role }}
          </h3>
          <h1 class="uppercase text-white font-bellefair text-[56px]">
            {{ content?.name }}
          </h1>
          <p
            class="text-textColor font-barlow text-[18px] leading-[32px] w-[444px] min-h-[160px]"
          >
            {{ content?.bio }}
          </p>
        </article>
        <nav class="mt-[88px] gap-[24px] flex mb-[94px]">
          <button
            class="w-[15px] aspect-square rounded-full bg-white/20 hover:bg-white/50 transition-all ease-in-out duration-300"
            [ngClass]="{'bg-white/100 hover:bg-white/100': content?.name === 'Douglas Hurley'}"
            (click)="toggle('Douglas Hurley')"
          ></button>
          <button
            class="w-[15px] aspect-square rounded-full bg-white/20 hover:bg-white/50 transition-all ease-in-out duration-300"
            [ngClass]="{'bg-white/100 hover:bg-white/100': content?.name === 'Mark Shuttleworth'}"
            (click)="toggle('Mark Shuttleworth')"
          ></button>
          <button
            class="w-[15px] aspect-square rounded-full bg-white/20 hover:bg-white/50 transition-all ease-in-out duration-300"
            [ngClass]="{'bg-white/100 hover:bg-white/100': content?.name === 'Victor Glover'}"
            (click)="toggle('Victor Glover')"
          ></button>
          <button
            class="w-[15px] aspect-square rounded-full bg-white/20 hover:bg-white/50 transition-all ease-in-out duration-300"
            [ngClass]="{'bg-white/100 hover:bg-white/100': content?.name === 'Anousheh Ansari'}"
            (click)="toggle('Anousheh Ansari')"
          ></button>
        </nav>
      </section>
      <figure class="flex justify-center items-center flex-1">
        <img [src]="content?.images?.png" alt="Crew Image" class="self-end" />
      </figure>
    </section>
  </section>
</main>

// src/view/components/Crew.tsx
import React, { useState } from 'react'
import Data from '../../model/data/data.json'

const datas = Data.crew

const Crew: React.FC = () => {
    const [currentDestination, setCurrentDestination] = useState(datas[0].name)

    const selected = datas.find(
        (element) => element.name === currentDestination
    )

    const onClickEvent = (value: string) => {
        setCurrentDestination(value)
    }

    return (
        <div className="m-auto flex w-[327px] flex-col items-center text-white md:mt-[40px] md:w-[691px] xl:mt-[62px] xl:w-[1138px] xl:flex-row">
            <div className="flex w-full flex-col xl:self-start">
                {/* Title*/}
                <h2 className="text-center tracking-[2.7px] md:text-left md:text-[20px] md:tracking-[3.38px] xl:text-[28px] xl:tracking-[4.72pxpx]">
                    <span className="mr-[18px] text-white/30">02</span>MEET YOUR
                    CREW
                </h2>
                {/* Image in mobile */}
                <div className="mt-[32px] flex w-full justify-center border-b-[1px] border-white/20 md:hidden">
                    <img
                        src={selected?.images.png.substring(1)}
                        alt="crew images"
                        className="h-[222px] w-[177.12px]"
                    />
                </div>
                {/* Button in mobile */}
                <div className="my-[32px] flex w-full justify-center gap-[16px] md:hidden">
                    {datas.map((data, i) => (
                        <button
                            key={i}
                            className={`h-[10px] w-[10px] rounded-full ${selected === data ? 'bg-white' : 'bg-white/40 hover:bg-white/60'}`}
                            onClick={() => onClickEvent(data.name)}
                        ></button>
                    ))}
                </div>
                {/* Name, Role, and Bio */}
                <div className="mb-[104px] w-full text-center md:m-auto md:mb-0 md:mt-[60px] md:w-[458px] xl:m-0 xl:mt-[154px] xl:w-[488.5px] xl:text-left">
                    <h1 className="text-white/70 md:text-[21px] xl:text-[32px]">
                        {selected?.role.toUpperCase()}
                    </h1>
                    <h1 className="mt-[8px] text-[24px] md:text-[40px] xl:mt-[15px] xl:text-[56px]">
                        {selected?.name.toUpperCase()}
                    </h1>
                    <p className="mt-[16px] leading-[25px] text-white/70 md:leading-[28px] xl:w-[444px] xl:text-[18px] xl:leading-[32px]">
                        {selected?.bio}
                    </p>
                </div>
                {/* Button in tablet and desktop*/}
                <div className="my-[40px] hidden w-full justify-center gap-[16px] md:flex xl:mt-[120px] xl:justify-start">
                    {datas.map((data, i) => (
                        <button
                            key={i}
                            className={`h-[10px] w-[10px] rounded-full ${selected === data ? 'bg-white' : 'bg-white/40 hover:bg-white/60'}`}
                            onClick={() => onClickEvent(data.name)}
                        ></button>
                    ))}
                </div>
            </div>
            {/* Image in tablet and desktop */}
            <div className="mt-[32px] hidden w-full justify-center md:mt-0 md:flex xl:self-end">
                <img
                    src={selected?.images.png.substring(1)}
                    alt="crew images"
                    className="h-[572px] w-[456.37px] xl:h-[712px] xl:w-[568.07px]"
                />
            </div>
        </div>
    )
}

export default Crew
