// src/app/pages/destination/destination.component.ts
import { CommonModule, NgClass, NgStyle } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { Destination, RootObject } from '../../interfaces/global';
import { GlobalService } from '../../services/global.service';
import {
  animate,
  state,
  style,
  transition,
  trigger,
  AnimationEvent,
} from '@angular/animations';

@Component({
  selector: 'app-destination',
  standalone: true,
  imports: [NgStyle, NgClass, CommonModule],
  templateUrl: './destination.component.html',
  styleUrl: './destination.component.css',
  animations: [
    trigger('myAnimation', [
      state('start', style({
        transform: 'translateX(0)',
        opacity: 1
      })),
      state('end', style({
        transform: 'translateX(-100px)',
        opacity: 0
      })),
      transition('start => end', animate('1s ease-in-out', style({
        transform: 'translateX(100px)',
        opacity: 0,
      }))),
      transition('end => start', animate('1s ease-in-out', style({
        transform: 'translateX(0)',
        opacity: 1,
      }))),
    ]),
    trigger('imageAnimation', [
      state('start', style({
        transform: 'scale(1)',
        opacity: 1
      })),
      state('end', style({
        transform: 'scale(1.5)',
        opacity: 0
      })),
      transition('start => end', animate('1s ease-in-out', style({
        transform: 'scale(0.2)',
        opacity: 0,
      }))),
      transition('end => start', animate('1s ease-in-out', style({
        transform: 'scale(1)',
        opacity: 1,
      }))),
    ]),
  ],
})
export class DestinationComponent {
  allData: RootObject = inject(GlobalService).globalData;
  planetData: Destination[];
  backgroundImage: string;
  state: string;
  content: Destination | undefined;
  query: string;

  constructor() {
    this.backgroundImage =
      "url('../../../assets/destination/background-destination-desktop.jpg')";
    this.planetData = this.allData.destinations;
    this.state = 'start';
    this.query = 'Moon';
    this.content = this.planetData.find((planet) => planet.name === this.query);
  }

  toggle(value: string): void {
    if(this.query !== value) {
      this.state = 'end';
      this.query = value;
    }
  }

  animationDone(event: AnimationEvent) {
    if (event.toState === 'end') {
      this.state = 'start';
      this.content = this.planetData.find((planet) => planet.name === this.query);
    }
  }
}

<main
  class="w-full min-h-screen bg-cover bg-center overflow-hidden flex justify-center bg-[#0B0D19]"
  [ngStyle]="{ 'background-image': backgroundImage }"
>
  <section
    class="pt-[88px] mobile:pt-[136px] tablet:pt-[212px] pb-[118px] w-full max-w-[1110px] px-[24px] mobile:px-[38.5px] tablet:px-[20px] flex flex-col animate-summon gap-[64px]"
  >
    <div
      class="font-barlowCondensed tracking-[4.725px] flex justify-center mobile:justify-start items-center gap-[28px] select-none"
    >
      <p
        class="text-white/[0.25] text-[16px] mobile:text-[20px] tablet:text-[28px] font-bold"
      >
        01
      </p>
      <p class="text-[16px] mobile:text-[20px] tablet:text-[28px] text-white">
        PICK YOUR DESTINATION
      </p>
    </div>
    <section
      class="flex flex-col tablet:flex-row justify-center items-center tablet:justify-between"
    >
      <figure
        class="flex-1 flex justify-center items-center w-full tablet:w-auto"
        [@imageAnimation]="state"
        (@imageAnimation.done)="animationDone($event)"
      >
        <img
          [src]="content?.images?.png"
          alt="Destination Image"
          class="animate-rotation rounded-full w-[60%] mobile:w-[40%] tablet:w-auto"
        />
      </figure>
      <section
        class="flex-1 tablet:pl-[100px] flex flex-col justify-center items-center tablet:block mt-[30px] mobile:mt-[60px] tablet:mt-0"
      >
        <nav class="flex gap-[26px] mobile:gap-[36px]">
          @for (name of planetNames; track name) {
          <button
            class="text-textColor tracking-[2.362px] mobile:tracking-[2.7px] font-barlowCondensed pb-[8px] mobile:pb-[12px] border-b-[3px] border-b-transparent hover:border-b-white/50 transition-all ease-in-out duration-300 uppercase text-[14px] mobile:text-[16px]"
            [ngClass]="{
              'border-b-white hover:border-b-white/100 text-white':
                content?.name === name
            }"
            (click)="toggle(name)"
          >
            {{ name }}
          </button>
          }
        </nav>
        <article
          [@myAnimation]="state"
          (@myAnimation.done)="animationDone($event)"
          class="flex flex-col justify-center items-center mt-[20px] mobile:mt-0 tablet:block select-none"
        >
          <h1
            class="text-white text-[56px] mobile:text-[80px] tablet:text-[100px] font-bellefair uppercase"
          >
            {{ content?.name }}
          </h1>
          <p
            class="text-textColor text-[15px] mobile:text-[16px] tablet:text-[18px] text-center tablet:text-left leading-[25px] mobile:leading-[28px] tablet:leading-[32px] max-w-[327] mobile:max-w-[573px] tablet:max-w-auto min-h-[125px] mobile:min-h-[100px] tablet:min-h-[170px]"
          >
            {{ content?.description }}
          </p>
          <div
            class="flex flex-col mobile:flex-row justify-center items-center mobile:items-start mobile:justify-around tablet:justify-start text-textColor border-t-[1px] border-t-[#383B4B] pt-[28px] w-full mt-[49px] tablet:mt-0 gap-[32px] mobile:gap-0"
          >
            <div
              class="tablet:flex-1 tablet:block flex flex-col justify-center items-center"
            >
              <p
                class="text-textColor text-[14px] font-barlowCondensed tracking-[2.362px]"
              >
                AVG. DISTANCE
              </p>
              <p class="text-white text-[28px] font-bellefair uppercase">
                {{ content?.distance }}
              </p>
            </div>
            <div
              class="tablet:flex-1 tablet:block flex flex-col justify-center items-center"
            >
              <p
                class="text-textColor text-[14px] font-barlowCondensed tracking-[2.362px]"
              >
                EST. TRAVEL TIME
              </p>
              <p class="text-white text-[28px] font-bellefair uppercase">
                {{ content?.travel }}
              </p>
            </div>
          </div>
        </article>
      </section>
    </section>
  </section>
</main>

// src/view/components/Destination.tsx
import React, { useState } from 'react'
import Data from '../../model/data/data.json'

const datas = Data.destinations

const Destination: React.FC = () => {
    const [currentDestination, setCurrentDestination] = useState(datas[0].name)

    const selected = datas.find(
        (element) => element.name === currentDestination
    )

    const onClickEvent = (value: string) => {
        setCurrentDestination(value)
    }

    return (
        <div className="m-auto flex w-[327px] flex-col items-center text-white md:mt-[40px] md:w-[691px] xl:mt-[76px] xl:w-[1110.5px]">
            <h2 className="text-center tracking-[2.7px] md:self-start md:text-[20px] md:tracking-[3.38px] xl:text-[28px] xl:tracking-[4.72px]">
                <span className="mr-[18px] text-white/30">01</span>PICK YOUR
                DESTINATION
            </h2>
            <div className="flex flex-col items-center justify-center xl:flex-row xl:gap-[157px]">
                <img
                    className="mt-[32px] h-[170px] w-[170px] animate-spin-slow md:mt-[60px] md:h-[300px] md:w-[300px] xl:h-[445px] xl:w-[445px]"
                    src={selected?.images.png.substring(1)}
                    alt="destination image"
                />
                <div className="flex flex-col items-center xl:w-[445px] xl:items-start">
                    <ul className="mt-[26px] flex gap-[26px] text-[14px] leading-[normal] tracking-[2.36px] md:mt-[53px] md:text-[16px] xl:gap-[35px] xl:tracking-[2.7px]">
                        {datas.map((data, i) => (
                            <li key={i}>
                                <button
                                    className={`border-b-[3px] pb-[8px] md:pb-[12px] ${data.name === currentDestination ? 'border-white' : 'border-white/0 text-white/70 hover:border-white/30'}`}
                                    onClick={() => onClickEvent(data.name)}
                                >
                                    {data.name}
                                </button>
                            </li>
                        ))}
                    </ul>
                    <h1 className="xl:text-100px] mt-[20px] text-[56px] md:mt-[32px] md:text-[80px]">
                        {selected?.name.toUpperCase()}
                    </h1>
                    <p className="w-[327px] text-center leading-[25px] text-white/80 md:w-[573px] xl:w-[445px] xl:text-left xl:text-[18px] xl:leading-[32px]">
                        {selected?.description}
                    </p>
                    <div className="mb-[58px] mt-[32px] w-full border-t-[1px] border-solid border-white/20 text-center md:mb-[62px] md:flex md:w-[573px] xl:mt-[54px] xl:w-[445px] xl:text-left">
                        <div className="flex-1">
                            <h2 className="mt-[32px] text-[14px] leading-[normal] tracking-[2.36px] text-white/60">
                                AVG. DISTANCE
                            </h2>
                            <h1 className="mt-[12px] text-[28px]">
                                {selected?.distance.toUpperCase()}
                            </h1>
                        </div>
                        <div className="flex-1">
                            <h2 className="mt-[32px] text-[14px] leading-[normal] tracking-[2.36px] text-white/60">
                                EST. TRAVEL TIME
                            </h2>
                            <h1 className="mt-[12px] text-[28px]">
                                {selected?.travel.toUpperCase()}
                            </h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Destination
